/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as FanRouteImport } from './routes/fan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as FanIndexRouteImport } from './routes/fan.index'
import { Route as StaffTranslateRouteImport } from './routes/staff.translate'
import { Route as StaffSecurityRouteImport } from './routes/staff.security'
import { Route as StaffQueueRouteImport } from './routes/staff.queue'
import { Route as StaffOrdersRouteImport } from './routes/staff.orders'
import { Route as StaffIncidentsRouteImport } from './routes/staff.incidents'
import { Route as StaffHelpQueueRouteImport } from './routes/staff.help-queue'
import { Route as StaffHeatmapRouteImport } from './routes/staff.heatmap'
import { Route as StaffFireRouteImport } from './routes/staff.fire'
import { Route as StaffCrowdRouteImport } from './routes/staff.crowd'
import { Route as StaffBroadcastRouteImport } from './routes/staff.broadcast'
import { Route as FanTicketRouteImport } from './routes/fan.ticket'
import { Route as FanNavigationRouteImport } from './routes/fan.navigation'
import { Route as FanHelpRouteImport } from './routes/fan.help'
import { Route as FanFoodRouteImport } from './routes/fan.food'
import { Route as FanFireSafetyRouteImport } from './routes/fan.fire-safety'
import { Route as FanEmergencyRouteImport } from './routes/fan.emergency'
import { Route as FanCrowdRouteImport } from './routes/fan.crowd'
import { Route as FanChatRouteImport } from './routes/fan.chat'
import { Route as FanAlertsRouteImport } from './routes/fan.alerts'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const FanRoute = FanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const FanIndexRoute = FanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FanRoute,
} as any)
const StaffTranslateRoute = StaffTranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => StaffRoute,
} as any)
const StaffSecurityRoute = StaffSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => StaffRoute,
} as any)
const StaffQueueRoute = StaffQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StaffRoute,
} as any)
const StaffIncidentsRoute = StaffIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHelpQueueRoute = StaffHelpQueueRouteImport.update({
  id: '/help-queue',
  path: '/help-queue',
  getParentRoute: () => StaffRoute,
} as any)
const StaffHeatmapRoute = StaffHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFireRoute = StaffFireRouteImport.update({
  id: '/fire',
  path: '/fire',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCrowdRoute = StaffCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => StaffRoute,
} as any)
const StaffBroadcastRoute = StaffBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => StaffRoute,
} as any)
const FanTicketRoute = FanTicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => FanRoute,
} as any)
const FanNavigationRoute = FanNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => FanRoute,
} as any)
const FanHelpRoute = FanHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => FanRoute,
} as any)
const FanFoodRoute = FanFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => FanRoute,
} as any)
const FanFireSafetyRoute = FanFireSafetyRouteImport.update({
  id: '/fire-safety',
  path: '/fire-safety',
  getParentRoute: () => FanRoute,
} as any)
const FanEmergencyRoute = FanEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => FanRoute,
} as any)
const FanCrowdRoute = FanCrowdRouteImport.update({
  id: '/crowd',
  path: '/crowd',
  getParentRoute: () => FanRoute,
} as any)
const FanChatRoute = FanChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => FanRoute,
} as any)
const FanAlertsRoute = FanAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => FanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fan': typeof FanRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/fan/alerts': typeof FanAlertsRoute
  '/fan/chat': typeof FanChatRoute
  '/fan/crowd': typeof FanCrowdRoute
  '/fan/emergency': typeof FanEmergencyRoute
  '/fan/fire-safety': typeof FanFireSafetyRoute
  '/fan/food': typeof FanFoodRoute
  '/fan/help': typeof FanHelpRoute
  '/fan/navigation': typeof FanNavigationRoute
  '/fan/ticket': typeof FanTicketRoute
  '/staff/broadcast': typeof StaffBroadcastRoute
  '/staff/crowd': typeof StaffCrowdRoute
  '/staff/fire': typeof StaffFireRoute
  '/staff/heatmap': typeof StaffHeatmapRoute
  '/staff/help-queue': typeof StaffHelpQueueRoute
  '/staff/incidents': typeof StaffIncidentsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/security': typeof StaffSecurityRoute
  '/staff/translate': typeof StaffTranslateRoute
  '/fan/': typeof FanIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fan/alerts': typeof FanAlertsRoute
  '/fan/chat': typeof FanChatRoute
  '/fan/crowd': typeof FanCrowdRoute
  '/fan/emergency': typeof FanEmergencyRoute
  '/fan/fire-safety': typeof FanFireSafetyRoute
  '/fan/food': typeof FanFoodRoute
  '/fan/help': typeof FanHelpRoute
  '/fan/navigation': typeof FanNavigationRoute
  '/fan/ticket': typeof FanTicketRoute
  '/staff/broadcast': typeof StaffBroadcastRoute
  '/staff/crowd': typeof StaffCrowdRoute
  '/staff/fire': typeof StaffFireRoute
  '/staff/heatmap': typeof StaffHeatmapRoute
  '/staff/help-queue': typeof StaffHelpQueueRoute
  '/staff/incidents': typeof StaffIncidentsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/security': typeof StaffSecurityRoute
  '/staff/translate': typeof StaffTranslateRoute
  '/fan': typeof FanIndexRoute
  '/staff': typeof StaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fan': typeof FanRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/fan/alerts': typeof FanAlertsRoute
  '/fan/chat': typeof FanChatRoute
  '/fan/crowd': typeof FanCrowdRoute
  '/fan/emergency': typeof FanEmergencyRoute
  '/fan/fire-safety': typeof FanFireSafetyRoute
  '/fan/food': typeof FanFoodRoute
  '/fan/help': typeof FanHelpRoute
  '/fan/navigation': typeof FanNavigationRoute
  '/fan/ticket': typeof FanTicketRoute
  '/staff/broadcast': typeof StaffBroadcastRoute
  '/staff/crowd': typeof StaffCrowdRoute
  '/staff/fire': typeof StaffFireRoute
  '/staff/heatmap': typeof StaffHeatmapRoute
  '/staff/help-queue': typeof StaffHelpQueueRoute
  '/staff/incidents': typeof StaffIncidentsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/queue': typeof StaffQueueRoute
  '/staff/security': typeof StaffSecurityRoute
  '/staff/translate': typeof StaffTranslateRoute
  '/fan/': typeof FanIndexRoute
  '/staff/': typeof StaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fan'
    | '/staff'
    | '/fan/alerts'
    | '/fan/chat'
    | '/fan/crowd'
    | '/fan/emergency'
    | '/fan/fire-safety'
    | '/fan/food'
    | '/fan/help'
    | '/fan/navigation'
    | '/fan/ticket'
    | '/staff/broadcast'
    | '/staff/crowd'
    | '/staff/fire'
    | '/staff/heatmap'
    | '/staff/help-queue'
    | '/staff/incidents'
    | '/staff/orders'
    | '/staff/queue'
    | '/staff/security'
    | '/staff/translate'
    | '/fan/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fan/alerts'
    | '/fan/chat'
    | '/fan/crowd'
    | '/fan/emergency'
    | '/fan/fire-safety'
    | '/fan/food'
    | '/fan/help'
    | '/fan/navigation'
    | '/fan/ticket'
    | '/staff/broadcast'
    | '/staff/crowd'
    | '/staff/fire'
    | '/staff/heatmap'
    | '/staff/help-queue'
    | '/staff/incidents'
    | '/staff/orders'
    | '/staff/queue'
    | '/staff/security'
    | '/staff/translate'
    | '/fan'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/fan'
    | '/staff'
    | '/fan/alerts'
    | '/fan/chat'
    | '/fan/crowd'
    | '/fan/emergency'
    | '/fan/fire-safety'
    | '/fan/food'
    | '/fan/help'
    | '/fan/navigation'
    | '/fan/ticket'
    | '/staff/broadcast'
    | '/staff/crowd'
    | '/staff/fire'
    | '/staff/heatmap'
    | '/staff/help-queue'
    | '/staff/incidents'
    | '/staff/orders'
    | '/staff/queue'
    | '/staff/security'
    | '/staff/translate'
    | '/fan/'
    | '/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FanRoute: typeof FanRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan': {
      id: '/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof FanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/fan/': {
      id: '/fan/'
      path: '/'
      fullPath: '/fan/'
      preLoaderRoute: typeof FanIndexRouteImport
      parentRoute: typeof FanRoute
    }
    '/staff/translate': {
      id: '/staff/translate'
      path: '/translate'
      fullPath: '/staff/translate'
      preLoaderRoute: typeof StaffTranslateRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/security': {
      id: '/staff/security'
      path: '/security'
      fullPath: '/staff/security'
      preLoaderRoute: typeof StaffSecurityRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/queue': {
      id: '/staff/queue'
      path: '/queue'
      fullPath: '/staff/queue'
      preLoaderRoute: typeof StaffQueueRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/incidents': {
      id: '/staff/incidents'
      path: '/incidents'
      fullPath: '/staff/incidents'
      preLoaderRoute: typeof StaffIncidentsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/help-queue': {
      id: '/staff/help-queue'
      path: '/help-queue'
      fullPath: '/staff/help-queue'
      preLoaderRoute: typeof StaffHelpQueueRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/heatmap': {
      id: '/staff/heatmap'
      path: '/heatmap'
      fullPath: '/staff/heatmap'
      preLoaderRoute: typeof StaffHeatmapRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/fire': {
      id: '/staff/fire'
      path: '/fire'
      fullPath: '/staff/fire'
      preLoaderRoute: typeof StaffFireRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/crowd': {
      id: '/staff/crowd'
      path: '/crowd'
      fullPath: '/staff/crowd'
      preLoaderRoute: typeof StaffCrowdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/broadcast': {
      id: '/staff/broadcast'
      path: '/broadcast'
      fullPath: '/staff/broadcast'
      preLoaderRoute: typeof StaffBroadcastRouteImport
      parentRoute: typeof StaffRoute
    }
    '/fan/ticket': {
      id: '/fan/ticket'
      path: '/ticket'
      fullPath: '/fan/ticket'
      preLoaderRoute: typeof FanTicketRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/navigation': {
      id: '/fan/navigation'
      path: '/navigation'
      fullPath: '/fan/navigation'
      preLoaderRoute: typeof FanNavigationRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/help': {
      id: '/fan/help'
      path: '/help'
      fullPath: '/fan/help'
      preLoaderRoute: typeof FanHelpRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/food': {
      id: '/fan/food'
      path: '/food'
      fullPath: '/fan/food'
      preLoaderRoute: typeof FanFoodRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/fire-safety': {
      id: '/fan/fire-safety'
      path: '/fire-safety'
      fullPath: '/fan/fire-safety'
      preLoaderRoute: typeof FanFireSafetyRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/emergency': {
      id: '/fan/emergency'
      path: '/emergency'
      fullPath: '/fan/emergency'
      preLoaderRoute: typeof FanEmergencyRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/crowd': {
      id: '/fan/crowd'
      path: '/crowd'
      fullPath: '/fan/crowd'
      preLoaderRoute: typeof FanCrowdRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/chat': {
      id: '/fan/chat'
      path: '/chat'
      fullPath: '/fan/chat'
      preLoaderRoute: typeof FanChatRouteImport
      parentRoute: typeof FanRoute
    }
    '/fan/alerts': {
      id: '/fan/alerts'
      path: '/alerts'
      fullPath: '/fan/alerts'
      preLoaderRoute: typeof FanAlertsRouteImport
      parentRoute: typeof FanRoute
    }
  }
}

interface FanRouteChildren {
  FanAlertsRoute: typeof FanAlertsRoute
  FanChatRoute: typeof FanChatRoute
  FanCrowdRoute: typeof FanCrowdRoute
  FanEmergencyRoute: typeof FanEmergencyRoute
  FanFireSafetyRoute: typeof FanFireSafetyRoute
  FanFoodRoute: typeof FanFoodRoute
  FanHelpRoute: typeof FanHelpRoute
  FanNavigationRoute: typeof FanNavigationRoute
  FanTicketRoute: typeof FanTicketRoute
  FanIndexRoute: typeof FanIndexRoute
}

const FanRouteChildren: FanRouteChildren = {
  FanAlertsRoute: FanAlertsRoute,
  FanChatRoute: FanChatRoute,
  FanCrowdRoute: FanCrowdRoute,
  FanEmergencyRoute: FanEmergencyRoute,
  FanFireSafetyRoute: FanFireSafetyRoute,
  FanFoodRoute: FanFoodRoute,
  FanHelpRoute: FanHelpRoute,
  FanNavigationRoute: FanNavigationRoute,
  FanTicketRoute: FanTicketRoute,
  FanIndexRoute: FanIndexRoute,
}

const FanRouteWithChildren = FanRoute._addFileChildren(FanRouteChildren)

interface StaffRouteChildren {
  StaffBroadcastRoute: typeof StaffBroadcastRoute
  StaffCrowdRoute: typeof StaffCrowdRoute
  StaffFireRoute: typeof StaffFireRoute
  StaffHeatmapRoute: typeof StaffHeatmapRoute
  StaffHelpQueueRoute: typeof StaffHelpQueueRoute
  StaffIncidentsRoute: typeof StaffIncidentsRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffQueueRoute: typeof StaffQueueRoute
  StaffSecurityRoute: typeof StaffSecurityRoute
  StaffTranslateRoute: typeof StaffTranslateRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffBroadcastRoute: StaffBroadcastRoute,
  StaffCrowdRoute: StaffCrowdRoute,
  StaffFireRoute: StaffFireRoute,
  StaffHeatmapRoute: StaffHeatmapRoute,
  StaffHelpQueueRoute: StaffHelpQueueRoute,
  StaffIncidentsRoute: StaffIncidentsRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffQueueRoute: StaffQueueRoute,
  StaffSecurityRoute: StaffSecurityRoute,
  StaffTranslateRoute: StaffTranslateRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FanRoute: FanRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
